language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t groberts99/docker-react -f Dockerfile.dev . 

script: 
  # - docker run -e CI=true groberts99/docker-react npm run test
  - docker run groberts99/docker-react npm run test -- --coverage